import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import {
  AccordionModule,
  UIShellModule,
  CodeSnippetModule,
  ModalModule,
  BreadcrumbModule,
  CheckboxModule,
  ButtonModule,
  ComboBoxModule,
  ContentSwitcherModule,
  DatePickerModule,
  DialogModule,
  DocumentationModule,
  DropdownModule,
  ExperimentalModule,
  FileUploaderModule,
  GridModule,
  HeaderModule,
  I18nModule,
  InlineLoadingModule,
  InputModule,
  LinkModule,
  ListModule,
  LoadingModule,
  NFormsModule,
  NotificationModule,
  NumberModule,
  PaginationModule,
  PanelModule,
  PlaceholderModule,
  ProgressIndicatorModule,
  RadioModule,
  SearchModule,
  SelectModule,
  SideNavModule,
  SliderModule,
  StructuredListModule,
  TableModule,
  TabsModule,
  TagModule,
  TilesModule,
  TimePickerModule,
  TimePickerSelectModule,
  ToggleModule
} from 'carbon-components-angular';

const modules = [
  AccordionModule,
  UIShellModule,
  CodeSnippetModule,
  ModalModule,
  BreadcrumbModule,
  CheckboxModule,
  ButtonModule,
  ComboBoxModule,
  ContentSwitcherModule,
  DatePickerModule,
  DialogModule,
  DocumentationModule,
  DropdownModule,
  ExperimentalModule,
  FileUploaderModule,
  GridModule,
  HeaderModule,
  I18nModule,
  InlineLoadingModule,
  InputModule,
  LinkModule,
  ListModule,
  LoadingModule,
  NFormsModule,
  NotificationModule,
  NumberModule,
  PaginationModule,
  PanelModule,
  PlaceholderModule,
  ProgressIndicatorModule,
  RadioModule,
  SearchModule,
  SelectModule,
  SideNavModule,
  SliderModule,
  StructuredListModule,
  TableModule,
  TabsModule,
  TagModule,
  TilesModule,
  TimePickerModule,
  TimePickerSelectModule,
  ToggleModule
];

@NgModule({
  declarations: [],
  imports: modules,
  exports: modules,
  providers: [],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class CarbonComponentsAngularModule { }